# File: ./docker/Dockerfile.dev
FROM node:22-alpine AS base

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && pnpm add -g turbo@^2

WORKDIR /app

# Menggunakan mode development
ENV NODE_ENV=development

# 💡 Untuk dev, kita cukup copy package.json & pnpm-lock untuk meng-install modul
COPY package.json pnpm-lock.yaml turbo.json ./
COPY apps/website/package.json ./apps/website/
COPY apps/spmb/package.json ./apps/spmb/
COPY apps/admin/package.json ./apps/admin/
COPY packages/ui/package.json ./packages/ui/
COPY packages/supabase/package.json ./packages/supabase/
COPY packages/validators/package.json ./packages/validators/
COPY packages/types/package.json ./packages/types/
COPY packages/tsconfig/package.json ./packages/tsconfig/

# Install semua dependencies (termasuk devDependencies)
RUN pnpm install

# Di level dev, source code TIDAK DI-COPY di sini, 
# melainkan di-mount via docker-compose agar HMR (Fast Refresh) aktif

ARG APP_NAME
ENV APP_NAME=${APP_NAME}

EXPOSE 3000

# Jalankan server dev bawaan aplikasi target
CMD ["sh", "-c", "pnpm --filter ${APP_NAME} dev"]