services:
  # -------------------------------------------------------
  # 1) Aplikasi Utama / Website (Port 3000)
  # -------------------------------------------------------
  website:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        APP_NAME: website # 💡 Mengarah ke apps/website
    container_name: bn_app_website
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env # Membaca file .env di root monorepo
    restart: always

  # -------------------------------------------------------
  # 2) Aplikasi SPMB (Port 3001)
  # -------------------------------------------------------
  spmb:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        APP_NAME: spmb # 💡 Mengarah ke apps/spmb
    container_name: bn_app_spmb
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env # Membaca file .env di root monorepo
    restart: always

  # -------------------------------------------------------
  # 3) Aplikasi Admin (Port 3002)
  # -------------------------------------------------------
  admin:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        APP_NAME: admin # 💡 Mengarah ke apps/admin
    container_name: bn_app_admin
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ../.env # Membaca file .env di root monorepo
    restart: always