name: Keep Supabase Alive

on:
  schedule:
    # Setiap jam 00:00 UTC pada tanggal 1, 7, 13, 19, 25, dan 31
    - cron: "0 0 1,7,13,19,25,31 * *"

  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Supabase Edge Function
        run: |
          curl -L -X POST "${{ secrets.SUPABASE_FUNCTION_URL }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_PUBLISHABLE_KEY }}" \
            -H "apikey: ${{ secrets.SUPABASE_PUBLISHABLE_KEY }}" \
            -H "Content-Type: application/json" \
            --data '{}'